- name: Cart Component
  hosts: cart
  become: yes
  tasks:
  - name: disable old nodejs andenable nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively removing app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download cart application
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/cart.zip
     dest: /tmp

  - name: Unzipping cart application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Installing Dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copying cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: deamon reload # After changing service file
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: restart and enable cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes

  
