- name: Catalogue Component
  hosts: catalogue
  vars:
    MONGODB_HOST: mongodb.techwithgopi.online
  become: yes
  tasks:
  - name: disable old nodejs andenable nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively removing app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue application
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
     dest: /tmp

  - name: Unzipping catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Installing Dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copying catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: deamon reload # After changing service file
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: get the catagories count
    ansible.builtin.command: mongo --host mongodb.techwithgopi.online --quiet -- eval 'db=db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count is: {{product_count}}"

  - name: Load catalogue data
    ansible.builtin.command: mongo --host {{MONGODB_HOST}} < /app/schema/catalogue.js
    when: product_count.stdout == "0"

  - name: restart and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes

  
  
  

  